# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: M2MzMWJjN2E2ZDNiMDRkZWZmYjRmZGY4MmVlNzMyOWFmYWI2ZTc3ZDUxZThhMDQzOGUwOGU4YTU3MWQ5ZjBkYTU3NTM1ZWFlMmVkNGRlMmQxNDA2ZmExMWYwZWNiYjdjMDQ3YmU4MTlmODc2ZGYzNGQ0NDQxMDUxYjdiNGVhNjE=
