export enum EstadoPublicacion {
  BORRADOR = 'BORRADOR',

  PUBLICADA = 'PUBLICADA',

  VISITA_AGENDADA = 'VISITA_AGENDADA',

  POSTULANTE_SELECCIONADO = 'POSTULANTE_SELECCIONADO',

  RESERVADA = 'RESERVADA',

  CONTRATO_EN_FIRMA = 'CONTRATO_EN_FIRMA',

  ARRENDADA = 'ARRENDADA',

  FINALIZADA = 'FINALIZADA',

  ARCHIVADA = 'ARCHIVADA',
}
