export enum EstadoUsuario {
  PENDIENTE_VERIFICACION = 'PENDIENTE_VERIFICACION',

  ACTIVO = 'ACTIVO',

  INACTIVO = 'INACTIVO',

  SUSPENDIDO = 'SUSPENDIDO',

  BLOQUEADO = 'BLOQUEADO',

  BANEADO = 'BANEADO',
}
