package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalificacionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAllPropertiesEquals(Calificacion expected, Calificacion actual) {
        assertCalificacionAutoGeneratedPropertiesEquals(expected, actual);
        assertCalificacionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAllUpdatablePropertiesEquals(Calificacion expected, Calificacion actual) {
        assertCalificacionUpdatableFieldsEquals(expected, actual);
        assertCalificacionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionAutoGeneratedPropertiesEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionUpdatableFieldsEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion relevant properties")
            .satisfies(a -> assertThat(a.getTipoCalificacion()).as("check tipoCalificacion").isEqualTo(expected.getTipoCalificacion()))
            .satisfies(a -> assertThat(a.getPuntaje()).as("check puntaje").isEqualTo(expected.getPuntaje()))
            .satisfies(a -> assertThat(a.getComentario()).as("check comentario").isEqualTo(expected.getComentario()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getVisible()).as("check visible").isEqualTo(expected.getVisible()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalificacionUpdatableRelationshipsEquals(Calificacion expected, Calificacion actual) {
        assertThat(actual)
            .as("Verify Calificacion relationships")
            .satisfies(a -> assertThat(a.getAutor()).as("check autor").isEqualTo(expected.getAutor()))
            .satisfies(a -> assertThat(a.getCalificado()).as("check calificado").isEqualTo(expected.getCalificado()))
            .satisfies(a -> assertThat(a.getContrato()).as("check contrato").isEqualTo(expected.getContrato()));
    }
}
