package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ContratoArriendoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoArriendoAllPropertiesEquals(ContratoArriendo expected, ContratoArriendo actual) {
        assertContratoArriendoAutoGeneratedPropertiesEquals(expected, actual);
        assertContratoArriendoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoArriendoAllUpdatablePropertiesEquals(ContratoArriendo expected, ContratoArriendo actual) {
        assertContratoArriendoUpdatableFieldsEquals(expected, actual);
        assertContratoArriendoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoArriendoAutoGeneratedPropertiesEquals(ContratoArriendo expected, ContratoArriendo actual) {
        assertThat(actual)
            .as("Verify ContratoArriendo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoArriendoUpdatableFieldsEquals(ContratoArriendo expected, ContratoArriendo actual) {
        assertThat(actual)
            .as("Verify ContratoArriendo relevant properties")
            .satisfies(a -> assertThat(a.getNumeroContrato()).as("check numeroContrato").isEqualTo(expected.getNumeroContrato()))
            .satisfies(a ->
                assertThat(a.getUrlContratoDigital()).as("check urlContratoDigital").isEqualTo(expected.getUrlContratoDigital())
            )
            .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
            .satisfies(a -> assertThat(a.getFechaFin()).as("check fechaFin").isEqualTo(expected.getFechaFin()))
            .satisfies(a -> assertThat(a.getValorMensual()).as("check valorMensual").isEqualTo(expected.getValorMensual()))
            .satisfies(a -> assertThat(a.getValorDeposito()).as("check valorDeposito").isEqualTo(expected.getValorDeposito()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaFirma()).as("check fechaFirma").isEqualTo(expected.getFechaFirma()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContratoArriendoUpdatableRelationshipsEquals(ContratoArriendo expected, ContratoArriendo actual) {
        assertThat(actual)
            .as("Verify ContratoArriendo relationships")
            .satisfies(a -> assertThat(a.getArrendador()).as("check arrendador").isEqualTo(expected.getArrendador()))
            .satisfies(a -> assertThat(a.getArrendatario()).as("check arrendatario").isEqualTo(expected.getArrendatario()))
            .satisfies(a -> assertThat(a.getInmueble()).as("check inmueble").isEqualTo(expected.getInmueble()));
    }
}
