package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentoUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUsuarioAllPropertiesEquals(DocumentoUsuario expected, DocumentoUsuario actual) {
        assertDocumentoUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentoUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUsuarioAllUpdatablePropertiesEquals(DocumentoUsuario expected, DocumentoUsuario actual) {
        assertDocumentoUsuarioUpdatableFieldsEquals(expected, actual);
        assertDocumentoUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUsuarioAutoGeneratedPropertiesEquals(DocumentoUsuario expected, DocumentoUsuario actual) {
        assertThat(actual)
            .as("Verify DocumentoUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUsuarioUpdatableFieldsEquals(DocumentoUsuario expected, DocumentoUsuario actual) {
        assertThat(actual)
            .as("Verify DocumentoUsuario relevant properties")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()))
            .satisfies(a -> assertThat(a.getNombreDocumento()).as("check nombreDocumento").isEqualTo(expected.getNombreDocumento()))
            .satisfies(a -> assertThat(a.getUrlArchivo()).as("check urlArchivo").isEqualTo(expected.getUrlArchivo()))
            .satisfies(a -> assertThat(a.getTipoMime()).as("check tipoMime").isEqualTo(expected.getTipoMime()))
            .satisfies(a -> assertThat(a.getTamanoArchivo()).as("check tamanoArchivo").isEqualTo(expected.getTamanoArchivo()))
            .satisfies(a -> assertThat(a.getFechaCarga()).as("check fechaCarga").isEqualTo(expected.getFechaCarga()))
            .satisfies(a -> assertThat(a.getAprobado()).as("check aprobado").isEqualTo(expected.getAprobado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUsuarioUpdatableRelationshipsEquals(DocumentoUsuario expected, DocumentoUsuario actual) {
        assertThat(actual)
            .as("Verify DocumentoUsuario relationships")
            .satisfies(a -> assertThat(a.getPerfilUsuario()).as("check perfilUsuario").isEqualTo(expected.getPerfilUsuario()));
    }
}
