package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InmuebleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAllPropertiesEquals(Inmueble expected, Inmueble actual) {
        assertInmuebleAutoGeneratedPropertiesEquals(expected, actual);
        assertInmuebleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAllUpdatablePropertiesEquals(Inmueble expected, Inmueble actual) {
        assertInmuebleUpdatableFieldsEquals(expected, actual);
        assertInmuebleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleAutoGeneratedPropertiesEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleUpdatableFieldsEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getCiudad()).as("check ciudad").isEqualTo(expected.getCiudad()))
            .satisfies(a -> assertThat(a.getLocalidad()).as("check localidad").isEqualTo(expected.getLocalidad()))
            .satisfies(a -> assertThat(a.getBarrio()).as("check barrio").isEqualTo(expected.getBarrio()))
            .satisfies(a -> assertThat(a.getLatitud()).as("check latitud").isEqualTo(expected.getLatitud()))
            .satisfies(a -> assertThat(a.getLongitud()).as("check longitud").isEqualTo(expected.getLongitud()))
            .satisfies(a -> assertThat(a.getTipoInmueble()).as("check tipoInmueble").isEqualTo(expected.getTipoInmueble()))
            .satisfies(a ->
                assertThat(a.getAreaMetrosCuadrados()).as("check areaMetrosCuadrados").isEqualTo(expected.getAreaMetrosCuadrados())
            )
            .satisfies(a ->
                assertThat(a.getNumeroHabitaciones()).as("check numeroHabitaciones").isEqualTo(expected.getNumeroHabitaciones())
            )
            .satisfies(a -> assertThat(a.getNumeroBanos()).as("check numeroBanos").isEqualTo(expected.getNumeroBanos()))
            .satisfies(a ->
                assertThat(a.getNumeroParqueaderos()).as("check numeroParqueaderos").isEqualTo(expected.getNumeroParqueaderos())
            )
            .satisfies(a -> assertThat(a.getEstrato()).as("check estrato").isEqualTo(expected.getEstrato()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInmuebleUpdatableRelationshipsEquals(Inmueble expected, Inmueble actual) {
        assertThat(actual)
            .as("Verify Inmueble relationships")
            .satisfies(a -> assertThat(a.getPropietario()).as("check propietario").isEqualTo(expected.getPropietario()));
    }
}
