package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MultimediaInmuebleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMultimediaInmuebleAllPropertiesEquals(MultimediaInmueble expected, MultimediaInmueble actual) {
        assertMultimediaInmuebleAutoGeneratedPropertiesEquals(expected, actual);
        assertMultimediaInmuebleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMultimediaInmuebleAllUpdatablePropertiesEquals(MultimediaInmueble expected, MultimediaInmueble actual) {
        assertMultimediaInmuebleUpdatableFieldsEquals(expected, actual);
        assertMultimediaInmuebleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMultimediaInmuebleAutoGeneratedPropertiesEquals(MultimediaInmueble expected, MultimediaInmueble actual) {
        assertThat(actual)
            .as("Verify MultimediaInmueble auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMultimediaInmuebleUpdatableFieldsEquals(MultimediaInmueble expected, MultimediaInmueble actual) {
        assertThat(actual)
            .as("Verify MultimediaInmueble relevant properties")
            .satisfies(a -> assertThat(a.getUrlMedia()).as("check urlMedia").isEqualTo(expected.getUrlMedia()))
            .satisfies(a -> assertThat(a.getTipoMedia()).as("check tipoMedia").isEqualTo(expected.getTipoMedia()))
            .satisfies(a -> assertThat(a.getPrincipal()).as("check principal").isEqualTo(expected.getPrincipal()))
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMultimediaInmuebleUpdatableRelationshipsEquals(MultimediaInmueble expected, MultimediaInmueble actual) {
        assertThat(actual)
            .as("Verify MultimediaInmueble relationships")
            .satisfies(a -> assertThat(a.getInmueble()).as("check inmueble").isEqualTo(expected.getInmueble()));
    }
}
