package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAllUpdatablePropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertPerfilUsuarioUpdatableFieldsEquals(expected, actual);
        assertPerfilUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioAutoGeneratedPropertiesEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(actual)
            .as("Verify PerfilUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableFieldsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        assertThat(actual)
            .as("Verify PerfilUsuario relevant properties")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()))
            .satisfies(a -> assertThat(a.getNumeroDocumento()).as("check numeroDocumento").isEqualTo(expected.getNumeroDocumento()))
            .satisfies(a -> assertThat(a.getPrimerNombre()).as("check primerNombre").isEqualTo(expected.getPrimerNombre()))
            .satisfies(a -> assertThat(a.getSegundoNombre()).as("check segundoNombre").isEqualTo(expected.getSegundoNombre()))
            .satisfies(a -> assertThat(a.getPrimerApellido()).as("check primerApellido").isEqualTo(expected.getPrimerApellido()))
            .satisfies(a -> assertThat(a.getSegundoApellido()).as("check segundoApellido").isEqualTo(expected.getSegundoApellido()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getDireccionActual()).as("check direccionActual").isEqualTo(expected.getDireccionActual()))
            .satisfies(a -> assertThat(a.getCiudad()).as("check ciudad").isEqualTo(expected.getCiudad()))
            .satisfies(a -> assertThat(a.getBarrio()).as("check barrio").isEqualTo(expected.getBarrio()))
            .satisfies(a -> assertThat(a.getProfesion()).as("check profesion").isEqualTo(expected.getProfesion()))
            .satisfies(a -> assertThat(a.getOcupacion()).as("check ocupacion").isEqualTo(expected.getOcupacion()))
            .satisfies(a -> assertThat(a.getEmpresaTrabajo()).as("check empresaTrabajo").isEqualTo(expected.getEmpresaTrabajo()))
            .satisfies(a -> assertThat(a.getUniversidad()).as("check universidad").isEqualTo(expected.getUniversidad()))
            .satisfies(a -> assertThat(a.getBiografia()).as("check biografia").isEqualTo(expected.getBiografia()))
            .satisfies(a -> assertThat(a.getIntereses()).as("check intereses").isEqualTo(expected.getIntereses()))
            .satisfies(a -> assertThat(a.getTieneMascotas()).as("check tieneMascotas").isEqualTo(expected.getTieneMascotas()))
            .satisfies(a -> assertThat(a.getFumador()).as("check fumador").isEqualTo(expected.getFumador()))
            .satisfies(a -> assertThat(a.getVerificado()).as("check verificado").isEqualTo(expected.getVerificado()))
            .satisfies(a -> assertThat(a.getHabilitadoRoomie()).as("check habilitadoRoomie").isEqualTo(expected.getHabilitadoRoomie()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilUsuarioUpdatableRelationshipsEquals(PerfilUsuario expected, PerfilUsuario actual) {
        // empty method
    }
}
