package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicacionInmuebleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionInmuebleAllPropertiesEquals(PublicacionInmueble expected, PublicacionInmueble actual) {
        assertPublicacionInmuebleAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicacionInmuebleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionInmuebleAllUpdatablePropertiesEquals(PublicacionInmueble expected, PublicacionInmueble actual) {
        assertPublicacionInmuebleUpdatableFieldsEquals(expected, actual);
        assertPublicacionInmuebleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionInmuebleAutoGeneratedPropertiesEquals(PublicacionInmueble expected, PublicacionInmueble actual) {
        assertThat(actual)
            .as("Verify PublicacionInmueble auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionInmuebleUpdatableFieldsEquals(PublicacionInmueble expected, PublicacionInmueble actual) {
        assertThat(actual)
            .as("Verify PublicacionInmueble relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCanonArriendo()).as("check canonArriendo").isEqualTo(expected.getCanonArriendo()))
            .satisfies(a -> assertThat(a.getDeposito()).as("check deposito").isEqualTo(expected.getDeposito()))
            .satisfies(a -> assertThat(a.getRequisitos()).as("check requisitos").isEqualTo(expected.getRequisitos()))
            .satisfies(a -> assertThat(a.getSeguroRequerido()).as("check seguroRequerido").isEqualTo(expected.getSeguroRequerido()))
            .satisfies(a ->
                assertThat(a.getDatacreditoRequerido()).as("check datacreditoRequerido").isEqualTo(expected.getDatacreditoRequerido())
            )
            .satisfies(a -> assertThat(a.getFechaDisponible()).as("check fechaDisponible").isEqualTo(expected.getFechaDisponible()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getPermiteRoomies()).as("check permiteRoomies").isEqualTo(expected.getPermiteRoomies()))
            .satisfies(a -> assertThat(a.getAceptaMascotas()).as("check aceptaMascotas").isEqualTo(expected.getAceptaMascotas()))
            .satisfies(a -> assertThat(a.getPermiteFumadores()).as("check permiteFumadores").isEqualTo(expected.getPermiteFumadores()))
            .satisfies(a -> assertThat(a.getPermiteNinos()).as("check permiteNinos").isEqualTo(expected.getPermiteNinos()))
            .satisfies(a -> assertThat(a.getPermiteVisitas()).as("check permiteVisitas").isEqualTo(expected.getPermiteVisitas()))
            .satisfies(a -> assertThat(a.getPermiteParejas()).as("check permiteParejas").isEqualTo(expected.getPermiteParejas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionInmuebleUpdatableRelationshipsEquals(PublicacionInmueble expected, PublicacionInmueble actual) {
        assertThat(actual)
            .as("Verify PublicacionInmueble relationships")
            .satisfies(a -> assertThat(a.getInmueble()).as("check inmueble").isEqualTo(expected.getInmueble()));
    }
}
