package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicacionRoomieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionRoomieAllPropertiesEquals(PublicacionRoomie expected, PublicacionRoomie actual) {
        assertPublicacionRoomieAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicacionRoomieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionRoomieAllUpdatablePropertiesEquals(PublicacionRoomie expected, PublicacionRoomie actual) {
        assertPublicacionRoomieUpdatableFieldsEquals(expected, actual);
        assertPublicacionRoomieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionRoomieAutoGeneratedPropertiesEquals(PublicacionRoomie expected, PublicacionRoomie actual) {
        assertThat(actual)
            .as("Verify PublicacionRoomie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionRoomieUpdatableFieldsEquals(PublicacionRoomie expected, PublicacionRoomie actual) {
        assertThat(actual)
            .as("Verify PublicacionRoomie relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getNombreHabitacion()).as("check nombreHabitacion").isEqualTo(expected.getNombreHabitacion()))
            .satisfies(a -> assertThat(a.getValorMensual()).as("check valorMensual").isEqualTo(expected.getValorMensual()))
            .satisfies(a ->
                assertThat(a.getServiciosIncluidos()).as("check serviciosIncluidos").isEqualTo(expected.getServiciosIncluidos())
            )
            .satisfies(a ->
                assertThat(a.getEspaciosCompartidos()).as("check espaciosCompartidos").isEqualTo(expected.getEspaciosCompartidos())
            )
            .satisfies(a -> assertThat(a.getGeneroPreferido()).as("check generoPreferido").isEqualTo(expected.getGeneroPreferido()))
            .satisfies(a -> assertThat(a.getFechaDisponible()).as("check fechaDisponible").isEqualTo(expected.getFechaDisponible()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicacionRoomieUpdatableRelationshipsEquals(PublicacionRoomie expected, PublicacionRoomie actual) {
        assertThat(actual)
            .as("Verify PublicacionRoomie relationships")
            .satisfies(a -> assertThat(a.getArrendatario()).as("check arrendatario").isEqualTo(expected.getArrendatario()))
            .satisfies(a -> assertThat(a.getInmueble()).as("check inmueble").isEqualTo(expected.getInmueble()));
    }
}
