package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolicitudArriendoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudArriendoAllPropertiesEquals(SolicitudArriendo expected, SolicitudArriendo actual) {
        assertSolicitudArriendoAutoGeneratedPropertiesEquals(expected, actual);
        assertSolicitudArriendoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudArriendoAllUpdatablePropertiesEquals(SolicitudArriendo expected, SolicitudArriendo actual) {
        assertSolicitudArriendoUpdatableFieldsEquals(expected, actual);
        assertSolicitudArriendoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudArriendoAutoGeneratedPropertiesEquals(SolicitudArriendo expected, SolicitudArriendo actual) {
        assertThat(actual)
            .as("Verify SolicitudArriendo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudArriendoUpdatableFieldsEquals(SolicitudArriendo expected, SolicitudArriendo actual) {
        assertThat(actual)
            .as("Verify SolicitudArriendo relevant properties")
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getAceptaTerminos()).as("check aceptaTerminos").isEqualTo(expected.getAceptaTerminos()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudArriendoUpdatableRelationshipsEquals(SolicitudArriendo expected, SolicitudArriendo actual) {
        assertThat(actual)
            .as("Verify SolicitudArriendo relationships")
            .satisfies(a -> assertThat(a.getArrendatario()).as("check arrendatario").isEqualTo(expected.getArrendatario()))
            .satisfies(a -> assertThat(a.getPublicacion()).as("check publicacion").isEqualTo(expected.getPublicacion()));
    }
}
