package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SolicitudRoomieAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudRoomieAllPropertiesEquals(SolicitudRoomie expected, SolicitudRoomie actual) {
        assertSolicitudRoomieAutoGeneratedPropertiesEquals(expected, actual);
        assertSolicitudRoomieAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudRoomieAllUpdatablePropertiesEquals(SolicitudRoomie expected, SolicitudRoomie actual) {
        assertSolicitudRoomieUpdatableFieldsEquals(expected, actual);
        assertSolicitudRoomieUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudRoomieAutoGeneratedPropertiesEquals(SolicitudRoomie expected, SolicitudRoomie actual) {
        assertThat(actual)
            .as("Verify SolicitudRoomie auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudRoomieUpdatableFieldsEquals(SolicitudRoomie expected, SolicitudRoomie actual) {
        assertThat(actual)
            .as("Verify SolicitudRoomie relevant properties")
            .satisfies(a -> assertThat(a.getMensaje()).as("check mensaje").isEqualTo(expected.getMensaje()))
            .satisfies(a -> assertThat(a.getReferencias()).as("check referencias").isEqualTo(expected.getReferencias()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSolicitudRoomieUpdatableRelationshipsEquals(SolicitudRoomie expected, SolicitudRoomie actual) {
        assertThat(actual)
            .as("Verify SolicitudRoomie relationships")
            .satisfies(a -> assertThat(a.getPostulante()).as("check postulante").isEqualTo(expected.getPostulante()))
            .satisfies(a -> assertThat(a.getPublicacionRoomie()).as("check publicacionRoomie").isEqualTo(expected.getPublicacionRoomie()));
    }
}
