package com.roomrent.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VisitaProgramadaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitaProgramadaAllPropertiesEquals(VisitaProgramada expected, VisitaProgramada actual) {
        assertVisitaProgramadaAutoGeneratedPropertiesEquals(expected, actual);
        assertVisitaProgramadaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitaProgramadaAllUpdatablePropertiesEquals(VisitaProgramada expected, VisitaProgramada actual) {
        assertVisitaProgramadaUpdatableFieldsEquals(expected, actual);
        assertVisitaProgramadaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitaProgramadaAutoGeneratedPropertiesEquals(VisitaProgramada expected, VisitaProgramada actual) {
        assertThat(actual)
            .as("Verify VisitaProgramada auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitaProgramadaUpdatableFieldsEquals(VisitaProgramada expected, VisitaProgramada actual) {
        assertThat(actual)
            .as("Verify VisitaProgramada relevant properties")
            .satisfies(a -> assertThat(a.getFechaSolicitada()).as("check fechaSolicitada").isEqualTo(expected.getFechaSolicitada()))
            .satisfies(a -> assertThat(a.getFechaConfirmada()).as("check fechaConfirmada").isEqualTo(expected.getFechaConfirmada()))
            .satisfies(a -> assertThat(a.getNotas()).as("check notas").isEqualTo(expected.getNotas()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVisitaProgramadaUpdatableRelationshipsEquals(VisitaProgramada expected, VisitaProgramada actual) {
        assertThat(actual)
            .as("Verify VisitaProgramada relationships")
            .satisfies(a -> assertThat(a.getVisitante()).as("check visitante").isEqualTo(expected.getVisitante()))
            .satisfies(a -> assertThat(a.getSolicitud()).as("check solicitud").isEqualTo(expected.getSolicitud()));
    }
}
